DOMAIN = "energy_planner"

DEFAULT_NAME = "Energy Planner"

CONF_BATTERY_SOC_ENTITY = "battery_soc_entity"
CONF_BATTERY_CAPACITY_ENTITY = "battery_capacity_entity"
CONF_BATTERY_MIN_SOC_ENTITY = "battery_min_soc_entity"
CONF_HOME_ENERGY_ENTITY = "home_energy_entity"
CONF_MANAGED_ENERGY_ENTITIES = "managed_energy_entities"
CONF_MANAGED_ENERGY_ENTITY = "managed_energy_entity"
CONF_MANAGED_LOAD_TYPE = "managed_load_type"
CONF_PRIORITY = "priority"
CONF_REQUESTED_ENERGY_ENTITY = "requested_energy_entity"
CONF_REQUIRED_ENERGY_ENTITY = "required_energy_entity"
# Kept only for migrating v3 electric-vehicle subentries.
CONF_MAXIMUM_CHARGING_POWER_ENTITY = "maximum_charging_power_entity"
CONF_MAXIMUM_CHARGING_POWER_KW = "maximum_charging_power_kw"
CONF_CHARGING_EFFICIENCY = "charging_efficiency"
CONF_TOP_TEMPERATURE_ENTITY = "top_temperature_entity"
CONF_BOTTOM_TEMPERATURE_ENTITY = "bottom_temperature_entity"
CONF_MINIMUM_TEMPERATURE_C = "minimum_temperature_c"
CONF_MAXIMUM_TEMPERATURE_C = "maximum_temperature_c"
CONF_TANK_VOLUME_LITERS = "tank_volume_liters"
CONF_HEATER_POWER_KW = "heater_power_kw"
CONF_THERMAL_CONVERSION_FACTOR = "thermal_conversion_factor"
CONF_SOLCAST_TODAY_ENTITY = "solcast_today_entity"
CONF_SOLCAST_TOMORROW_ENTITY = "solcast_tomorrow_entity"
CONF_SOLCAST_ADDITIONAL_ENTITIES = "solcast_additional_entities"

CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"
CONF_HISTORY_LEARNING_DAYS = "history_learning_days"
CONF_INTERVAL_MINUTES = "interval_minutes"
CONF_HISTORY_CORRECTION_PERCENT = "history_correction_percent"
CONF_MIN_BASELINE_KWH_PER_HOUR = "min_baseline_kwh_per_hour"
CONF_GRID_CHARGING_ENABLED = "grid_charging_enabled"
CONF_GRID_CHARGE_MAX_KW = "grid_charge_max_kw"
CONF_GRID_CHARGE_EFFICIENCY = "grid_charge_efficiency"
CONF_SOC_RESERVE_PERCENT = "soc_reserve_percent"
CONF_SOC_EPS_KWH = "soc_eps_kwh"
CONF_NT_WINDOWS = "nt_windows"
CONF_NT_WINDOWS_ENABLED = "nt_windows_enabled"
CONF_CHARGE_WINDOW = "charge_window"
CONF_NT_WINDOW_1_START = "nt_window_1_start"
CONF_NT_WINDOW_1_END = "nt_window_1_end"
CONF_NT_WINDOW_2_START = "nt_window_2_start"
CONF_NT_WINDOW_2_END = "nt_window_2_end"
CONF_CHARGE_WINDOW_START = "charge_window_start"
CONF_CHARGE_WINDOW_END = "charge_window_end"
CONF_SUN_START_REQUIRED_MINUTES = "sun_start_required_minutes"
CONF_FORECAST_HORIZON_HOURS = "forecast_horizon_hours"

DEFAULT_UPDATE_INTERVAL_MINUTES = 60
DEFAULT_HISTORY_LEARNING_DAYS = 3
DEFAULT_MANAGED_HISTORY_LEARNING_DAYS = 7
DEFAULT_DAILY_HISTORY_MIN_COVERAGE_RATIO = 0.75
DEFAULT_INTERVAL_MINUTES = 5
DEFAULT_HISTORY_RETENTION_DAYS = 30
DEFAULT_HISTORY_CORRECTION_PERCENT = 5.0
DEFAULT_HISTORY_PROFILE_MARGIN_PERCENT = 5.0
DEFAULT_MIN_BASELINE_KWH_PER_HOUR = 0.2
DEFAULT_GRID_CHARGING_ENABLED = True
DEFAULT_GRID_CHARGE_MAX_KW = 5.5
DEFAULT_GRID_CHARGE_EFFICIENCY = 0.92
DEFAULT_SOC_RESERVE_PERCENT = 1
DEFAULT_SOC_EPS_KWH = 0.02
DEFAULT_SUN_START_REQUIRED_MINUTES = 30
DEFAULT_FORECAST_HORIZON_HOURS = 48

MANAGED_LOAD_SUBENTRY = "managed_load"
MANAGED_LOAD_TYPE_GENERIC = "generic"
MANAGED_LOAD_TYPE_HOT_WATER = "hot_water"
MANAGED_LOAD_TYPE_ELECTRIC_VEHICLE = "electric_vehicle"

DEFAULT_MANAGED_LOAD_TYPE = MANAGED_LOAD_TYPE_GENERIC
DEFAULT_MANAGED_LOAD_PRIORITY = 100
DEFAULT_HOT_WATER_MAXIMUM_TEMPERATURE_C = 70.0
DEFAULT_HOT_WATER_THERMAL_CONVERSION_FACTOR = 1.0
DEFAULT_EV_MAXIMUM_CHARGING_POWER_KW = 11.0
DEFAULT_EV_CHARGING_EFFICIENCY = 0.90

DEFAULT_NT_WINDOWS = [
    {"start": "17:00", "end": "19:00"},
    {"start": "22:00", "end": "04:00"},
]
DEFAULT_CHARGE_WINDOW = {"start": "22:00", "end": "04:00"}
